# Generated by Django 3.2.6 on 2022-04-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_account', '0002_remove_user_email_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Terms_and_condition_agreement',
            new_name='terms_and_condition_agreement',
        ),
    ]
